name: 构建ACE3内核-KernelSU-SFS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 最大化构建空间
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 8192
        temp-reserve-mb: 2048
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        
    - name: 配置 Git
      run: |
         git config --global user.name "yuanqiongyoukong"
         git config --global user.email "413722718@qq.com"
         
    - name: 安装编译环境
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install ccache curl git repo python3 python-is-python3 -y
        
    - name: 拉取内核清单
      run: |
        mkdir kernel_workspace && cd kernel_workspace
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8550 -m oneplus_ace3_v.xml --depth=1
        repo sync  -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
        
    - name: 添加KernelSU
      run: |
        cd kernel_workspace/kernel_platform
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
        
    - name: 添加SUSFS
      run: |
        cd kernel_workspace
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android13-5.15
        cd kernel_platform
        cp ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU/
        cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch ./common/
        cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
        cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
        # 应用补丁
        cd ./KernelSU
        patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
        cd ../common
        patch -p1 < 50_add_susfs_in_gki-android13-5.15.patch || true
        
    - name: 编译内核
      run: |
        cd kernel_workspace
        export LTO=thin
        ./kernel_platform/oplus/build/oplus_build_kernel.sh kalama gki
        
    - name: 上传 Image
      uses: actions/upload-artifact@v4
      with:
        name: Image-KernelSU-SUSFS
        path: kernel_workspace/out/dist/Image
