name: 构建ksu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 8192
        temp-reserve-mb: 2048
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        
    - name: 初始化编译环境
      run: |
        git config --global user.name  "yuanqiongyoukong"
        git config --global user.email  "413722718@qq.com" 
        sudo apt update && sudo apt upgrade -y
        sudo apt install ccache curl git repo python3 python-is-python3 -y

    - name: 拉取内核清单及相关操作
      run: |
        mkdir -p kernel && cd kernel
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8550 -m oneplus_12r_v.xml --depth=1
        repo sync -j$(nproc --all)
        rm -f common/android/abi_gki_protected_exports_* msm-kernel/android/abi_gki_protected_exports_* 2>/dev/null
        sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion kernel_platform/msm-kernel/scripts/setlocalversion
        sed -i '203a\export LTO=thin' kernel_platform/oplus/build/oplus_setup.sh                                                # 启用ThinLTO优化
        sed -i 's/export REPACK_IMG=true/export REPACK_IMG=false/Ig' kernel_platform/oplus/build/oplus_setup.sh                 # 禁用图像打包
        sed -i 's/local default_value=none/local default_value=thin/Ig' kernel_platform/oplus/build/oplus_setup.sh              # 设置默认值为thin
        # sed -i 's/local default_value=enable/local default_value=disable/Ig' kernel_platform/oplus/build/oplus_setup.sh         # 设置默认值为禁用

    - name: 设置 KernelSU
      run: |
        cd kernel/kernel_platform/common
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh"  | bash -s main
        
    - name: 添加 SUSFS
      run: |
        cd kernel
        git clone https://gitlab.com/simonpunk/susfs4ksu.git  -b gki-android13-5.15
        cd kernel_platform
        cp ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./common/KernelSU/
        cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch ./common/
        cp -r ../susfs4ksu/kernel_patches/fs/* ./common/fs/
        cp -r ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/

        # Apply patches
        cd ./common/KernelSU
        patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
        cd ..
        patch -p1 < 50_add_susfs_in_gki-android13-5.15.patch || true

    - name: 编译内核
      run: |
        cd kernel
        ./kernel_platform/oplus/build/oplus_build_kernel.sh kalama gki

    - name: 制作 AnyKernel3
      run: |
        cd kernel
        git clone https://github.com/Kernel-SU/AnyKernel3  --depth=1
        rm -rf ./AnyKernel3/.git ./AnyKernel3/LICENSE
        cp out/dist/Image AnyKernel3/
      continue-on-error: true 

    - name: 上传 AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-KernelSU_Next-SUSFS
        path: kernel/AnyKernel3
      continue-on-error: true 

    - name: 上传 Image
      uses: actions/upload-artifact@v4
      with:
        name: Image-KernelSU_Next-SUSFS
        path: kernel/out/dist/Image
      continue-on-error: true 
