name: 构建KernelSU

on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true 
        default: 'sm8550'
      FEIL:
        description: "配置文件"
        required: true 
        default: 'oneplus_ace3_v'
      CPUD:
        description: "处理器代号"
        required: true 
        default: 'kalama'
      ANDROID_VERSION:
        description: "内核安卓版本"
        required: true 
        default: 'android13'
      KERNEL_VERSION:
        description: "内核版本"
        required: true 
        default: '5.15'
        
env:
  KERNELSU_DIR: KernelSU
  WORKSPACE_DIR: kernel_workspace
  PLATFORM_DIR: kernel_platform
  GIT_USER_NAME: yuanqiongyoukong
  GIT_USER_EMAIL: 413722718@qq.com
  KERNEL_MANIFEST_URL: https://github.com/OnePlusOSS/kernel_manifest.git
  KERNELSU_URL: https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh
  SUSFS_REPO: https://gitlab.com/simonpunk/susfs4ksu.git
  PATCHES_REPO: https://github.com/TheWildJames/kernel_patches.git
  ANYKERNEL3_REPO: https://github.com/Kernel-SU/AnyKernel3
  BUILD_KERNEL: kernel_platform/oplus/build/oplus_setup.sh
  UPLOAD_IMAGE: kernel_workspace/out/dist/Image
  UPLOAD_ANYKERNEL3: AnyKernel3.zip
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 最大化构建空间
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 8192
        temp-reserve-mb: 2048
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        
    - name: 配置 Git
      run: |
        git config --global user.name "${GIT_USER_NAME}"
        git config --global user.email "${GIT_USER_EMAIL}"
        
    - name: 安装编译环境
      run: |
        sudo apt update && sudo apt upgrade -y && sudo apt install -y python3 git curl
        curl -o ~/repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo

    - name: 拉取内核清单
      run: |
        mkdir ${{env.WORKSPACE_DIR}} && cd ${{env.WORKSPACE_DIR}}
        repo init -u ${{env.KERNEL_MANIFEST_URL}} -b refs/heads/oneplus/${{github.event.inputs.CPU}} -m ${{github.event.inputs.FEIL}}.xml --depth=1
        repo sync
        rm -f common/android/abi_gki_protected_exports_* msm-kernel/android/abi_gki_protected_exports_* 2>/dev/null || echo "No protected exports found!"
        sed -i 's/ -dirty//g' ${{env.PLATFORM_DIR}}/common/scripts/setlocalversion ${{env.PLATFORM_DIR}}/msm-kernel/scripts/setlocalversion
        sed -i '203a\export LTO=thin' ${{env.PLATFORM_DIR}}/${{env.BUILD_KERNEL}}                                                # 启用ThinLTO优化
        # sed -i 's/export REPACK_IMG=true/export REPACK_IMG=false/Ig' ${{env.PLATFORM_DIR}}/${{env.BUILD_KERNEL}}                 # 禁用图像打包
        # sed -i 's/local default_value=none/local default_value=thin/Ig' ${{env.PLATFORM_DIR}}/${{env.BUILD_KERNEL}}              # 设置默认值为thin
        # sed -i 's/local default_value=enable/local default_value=disable/Ig' ${{env.PLATFORM_DIR}}/${{env.BUILD_KERNEL}}         # 设置默认值为禁用
        
    - name: 设置 KernelSU
      run: |
        cd ${{env.WORKSPACE_DIR}}/${{env.PLATFORM_DIR}}/common
        curl -LSs ${{env.KERNELSU_URL}} | bash -s main
        cd ${KERNELSU_DIR}
        KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
        echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
        sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
        
    - name: 添加 SUSFS
      run: |
        cd ${{env.WORKSPACE_DIR}}
        git clone ${{env.SUSFS_REPO}} -b gki-${{github.event.inputs.ANDROID_VERSION}}-${{github.event.inputs.KERNEL_VERSION}}
        git clone ${{env.PATCHES_REPO}}
        cd ${{env.PLATFORM_DIR}}
        cp ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./common/${KERNELSU_DIR}/
        cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{github.event.inputs.ANDROID_VERSION}}-${{github.event.inputs.KERNEL_VERSION}}.patch ./common/
        cp -r ../susfs4ksu/kernel_patches/fs/* ./common/fs/
        cp -r ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
        
        # 应用补丁
        cd ./common/${KERNELSU_DIR}
        patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
        cd ..
        patch -p1 < 50_add_susfs_in_gki-android13-5.15.patch || true
        cd ../../kernel_patches/
        sed -i -e 's/KernelSU-Next/KernelSU/g' apk_sign.c_fix.patch  core_hook.c_fix.patch  selinux.c_fix.patch 
        cp 69_hide_stuff.patch ./
        patch -p1 -F 3 < 69_hide_stuff.patch
        cp apk_sign.c_fix.patch ./
        patch -p1 -F 3 < apk_sign.c_fix.patch
        cp core_hook.c_fix.patch ./
        patch -p1 --fuzz=3 < ./core_hook.c_fix.patch
        cp selinux.c_fix.patch ./
        patch -p1 -F 3 < selinux.c_fix.patch
        
    - name: 编译内核
      run: |
        cd ${{env.WORKSPACE_DIR}}
        ./${{env.BUILD_KERNEL}} ${{github.event.inputs.CPUD}} gki

    - name: 制作 AnyKernel3
      run: |
        git clone ${{env.ANYKERNEL3_REPO}} --depth=1
        rm -rf ./AnyKernel3/.git
        cp ${{env.UPLOAD_IMAGE}} ./AnyKernel3/Image
        
    - name: 上传 AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3_${KERNELSU_DIR}_${env.KSUVER}_${{github.event.inputs.FEIL}}
        path: ./${{UPLOAD_ANYKERNEL3}}
        
    - name: 上传 Image
      uses: actions/upload-artifact@v4
      with:
        name: Image-${KERNELSU_DIR}_${env.KSUVER}_${{github.event.inputs.FEIL}}
        path: ./${{env.UPLOAD_IMAGE}}
