name: 构建KernelSU
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true 
        default: 'sm8550'
      FEIL:
        description: "配置文件"
        required: true 
        default: 'oneplus_ace3_v'
      CPUD:
        description: "处理器代号"
        required: true 
        default: 'kalama'
      ANDROID_VERSION:
        description: "内核安卓版本"
        required: true 
        default: 'android13'
      KERNEL_VERSION:
        description: "内核版本"
        required: true 
        default: '5.15'
      KSU_ENABLED:
        description: "添加 KernelSU"
        required: true 
        type: boolean
        default: true 
      KSU_VERSION:
        description: "ksu版本"
        required: true 
        type: choice
        options:
          - ksu
          - ksuci
          - mksu
      SUSFS_ENABLED:
        description: "添加 SUSFS"
        required: true 
        type: boolean
        default: true 
      PATCH_VERSION:
        description: "补丁版本"
        required: true 
        type: choice
        options:
          - ksu
          - mksu
      KERNEL_NAME:
        description: "自定义内核后版本名"
        required: false 
        default: ''
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 最大化构建空间
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 8192
        temp-reserve-mb: 2048
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        
    - name: 初始化编译环境
      run: |
        git config --global user.name "yuanqiongyoukong"
        git config --global user.email "413722718@qq.com"
        sudo apt update && sudo apt upgrade -y && sudo apt install -y python3 git curl
        curl -o ~/repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo
        
    - name: 拉取内核清单
      run: |
        mkdir kernel_workspace && cd kernel_workspace
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/${{ github.event.inputs.CPU }} -m ${{ github.event.inputs.FEIL }}.xml --depth=1
        repo sync -c -j$(nproc --all) --no-tags
        rm -f ./kernel_platform/common/android/abi_gki_protected_exports_* ./kernel_platform/msm-kernel/android/abi_gki_protected_exports_* 2>/dev/null || echo "No protected exports found!"
        sed -i 's/ -dirty//g' ./kernel_platform/common/scripts/setlocalversion ./kernel_platform/msm-kernel/scripts/setlocalversion ./kernel_platform/external/dtc/scripts/setlocalversion
        if [ -n "${{ github.event.inputs.KERNEL_NAME }}" ]; then
          sed -i '$s|echo "\$res"|echo "-${{ github.event.inputs.KERNEL_NAME }}"|' ./kernel_platform/common/scripts/setlocalversion
        fi
        git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
        rm -rf ./AnyKernel3/.git

    - name: 添加 KernelSU
      if: github.event.inputs.KSU_ENABLED == 'true' && github.event.inputs.KSU_VERSION == 'ksu'
      run: |
        cd kernel_workspace/kernel_platform
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
        cd KernelSU
        KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
        echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
        sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

    - name: 添加 KernelSU CI
      if: github.event.inputs.KSU_ENABLED == 'true' && github.event.inputs.KSU_VERSION == 'ksuci'
      run: |
        cd kernel_workspace/kernel_platform
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
        cd KernelSU
        git revert -m 1 $(git log --grep="remove devpts hook" --pretty=format:"%H") -n
        KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
        echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
        sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

    - name: 添加 MKernelSU
      if: github.event.inputs.KSU_ENABLED == 'true' && github.event.inputs.KSU_VERSION == 'mksu'
      run: |
        cd kernel_workspace/kernel_platform
        curl -LSs "https://raw.githubusercontent.com/5ec1cff/KernelSU/refs/heads/main/kernel/setup.sh" | bash -
        cd KernelSU
        git revert -m 1 $(git log --grep="remove devpts hook" --pretty=format:"%H") -n
        KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
        echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
        sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
        
    - name: 添加 SUSFS
      if: github.event.inputs.SUSFS_ENABLED == 'true'
      run: |
        cd kernel_workspace
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }} --depth 1
        cd kernel_platform
        cp ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU/
        cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch ./common/
        cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
        cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
        
        # 应用补丁
        cd ./KernelSU
        patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
        cd ../common
        patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true
        
    - name: Mksu 补丁
      if: github.event.inputs.SUSFS_ENABLED == 'true' && github.event.inputs.PATCH_VERSION == 'mksu'
      run: |
        cd kernel_workspace
        git clone https://github.com/WildPlusKernel/kernel_patches.git --depth 1
        git clone https://github.com/yuhangle/Action-KernelSU-Next -b dev --depth 1
        cd kernel_platform
        cp ../kernel_patches/mksu/mksu_susfs.patch ./KernelSU/
        cp ../Action-KernelSU-Next/mksu_patch/kernel/* ./KernelSU/
        
        # 应用补丁
        cd ./KernelSU
        patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
        patch -p1 --forward < mksu_susfs.patch || true
        cd kernel
        patch < ../core_hook.c.patch || true
        patch < ../sucompat.c.patch || true
        cd ../../common
        cp ../../kernel_patches/69_hide_stuff.patch ./
        patch -p1 -F 3 < 69_hide_stuff.patch
        
    - name: 编译内核
      run: |
        cd kernel_workspace
        LTO=thin ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ github.event.inputs.CPUD }} gki
        
    - name: 制作 AnyKernel3
      run: |
        mv kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-gki/gki_kernel/dist/Image kernel_workspace/AnyKernel3/
      continue-on-error: true 
        
    - name: 上传 AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3_KernelSU_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
        path: kernel_workspace/AnyKernel3/*
      continue-on-error: true 
        
    - name: 上传 Image
      uses: actions/upload-artifact@v4
      with:
        name: Image_KernelSU_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
        path: kernel_workspace/AnyKernel3/Image
      continue-on-error: true 
